//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id_evento { get; set; }
        public string nome_evt { get; set; }
        public System.DateTime data_evt { get; set; }
        public string contato_evt { get; set; }
    }
}
